name: .NET

on:
  push:
  pull_request:
    branches: [ dotnetcore ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore RTSP.sln
    - name: Build
      run: dotnet build --no-restore RTSP.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal RTSP.sln
